### PR TITLE
BDP strategies for WBTC, WETH, USDT, USDC

### PR DESCRIPTION
**Pull request by JasperSlimmens**
I wrote strategies to farm BDP ([https://www.bigdataprotocol.com/datavault](https://www.bigdataprotocol.com/datavault)). They have a short term mining program that will give rewards until 12th of March 4pm GMT. So we might be a little late to the party, but rewards are very decent for single assets pools, so it might be interesting to switch for the few days that are left.

Their reward pool is same as the sushi MasterChef contract, containing all reward pools in a single contract. So these strategies are straightforward implementations of the MasterChefStrategy. Test results are shown below.

All tests were run at blockNumber 11998000.

WBTC: `npx hardhat test test/bdp/wbtc.js`
```
  BDP: WBTC
Impersonating...
0xf00dD244228F51547f0563e60bCa65a30FBF5f7f
0x6daB3bCbFb336b29d06B9C793AEF7eaA57888922
Fetching Underlying at:  0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599
New Vault Deployed:  0xc228F1712588D45c6D689315Cc1A3e96aD4B2146
Strategy Deployed:  0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512
Strategy and vault added to Controller.
    Happy path
loop  0
old shareprice:  100000000
new shareprice:  100000000
growth:  1
loop  1
old shareprice:  100000000
new shareprice:  100030997
growth:  1.00030997
loop  2
old shareprice:  100030997
new shareprice:  100061890
growth:  1.0003088342706412
loop  3
old shareprice:  100061890
new shareprice:  100092679
growth:  1.0003076995647393
loop  4
old shareprice:  100092679
new shareprice:  100123365
growth:  1.0003065758685508
loop  5
old shareprice:  100123365
new shareprice:  100153949
growth:  1.000305463165366
loop  6
old shareprice:  100153949
new shareprice:  100184430
growth:  1.0003043414693513
loop  7
old shareprice:  100184430
new shareprice:  100214810
growth:  1.0003032407331158
loop  8
old shareprice:  100214810
new shareprice:  100245089
growth:  1.0003021409709802
loop  9
old shareprice:  100245089
new shareprice:  100275266
growth:  1.0003010322031836
vaultBalance:  105103425929
earned!
      √ Farmer should earn money

1 passing (1m)
```

WETH: `npx hardhat test test/bdp/weth.js`
```
  BDP: WETH
Impersonating...
0xf00dD244228F51547f0563e60bCa65a30FBF5f7f
0x6daB3bCbFb336b29d06B9C793AEF7eaA57888922
Fetching Underlying at:  0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2
New Vault Deployed:  0xc228F1712588D45c6D689315Cc1A3e96aD4B2146
Strategy Deployed:  0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512
Strategy and vault added to Controller.
    Happy path
loop  0
old shareprice:  1000000000000000000
new shareprice:  1000000000000000000
growth:  1
loop  1
old shareprice:  1000000000000000000
new shareprice:  1000166900801109344
growth:  1.0001669008011094
loop  2
old shareprice:  1000166900801109344
new shareprice:  1000333529250523006
growth:  1.0001666006436327
loop  3
old shareprice:  1000333529250523006
new shareprice:  1000499885963975323
growth:  1.000166301247122
loop  4
old shareprice:  1000499885963975323
new shareprice:  1000665971555486662
growth:  1.0001660026091372
loop  5
old shareprice:  1000665971555486662
new shareprice:  1000831786637374040
growth:  1.0001657047272523
loop  6
old shareprice:  1000831786637374040
new shareprice:  1000997331820252572
growth:  1.0001654075990478
loop  7
old shareprice:  1000997331820252572
new shareprice:  1001162607713040835
growth:  1.0001651112221126
loop  8
old shareprice:  1001162607713040835
new shareprice:  1001327614922967512
growth:  1.0001648155940457
loop  9
old shareprice:  1001327614922967512
new shareprice:  1001492354055578003
growth:  1.0001645207124574
vaultBalance:  29655102071068088406192
earned!
      √ Farmer should earn money

  1 passing (1m)
```

USDT: `npx hardhat test test/bdp/usdt.js`
```
  BDP: USDT
Impersonating...
0xf00dD244228F51547f0563e60bCa65a30FBF5f7f
0x73631ccaefc7AD7434018BC48b01576aBFaB3480
Fetching Underlying at:  0xdAC17F958D2ee523a2206206994597C13D831ec7
New Vault Deployed:  0xc228F1712588D45c6D689315Cc1A3e96aD4B2146
Strategy Deployed:  0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512
Strategy and vault added to Controller.
    Happy path
loop  0
old shareprice:  1000000
new shareprice:  1000000
growth:  1
loop  1
old shareprice:  1000000
new shareprice:  1000390
growth:  1.00039
loop  2
old shareprice:  1000390
new shareprice:  1000778
growth:  1.000387848738992
loop  3
old shareprice:  1000778
new shareprice:  1001165
growth:  1.0003866991480628
loop  4
old shareprice:  1001165
new shareprice:  1001550
growth:  1.0003845519969237
loop  5
old shareprice:  1001550
new shareprice:  1001934
growth:  1.0003834057211323
loop  6
old shareprice:  1001934
new shareprice:  1002315
growth:  1.0003802645683249
loop  7
old shareprice:  1002315
new shareprice:  1002695
growth:  1.000379122331802
loop  8
old shareprice:  1002695
new shareprice:  1003073
growth:  1.0003769840280443
loop  9
old shareprice:  1003073
new shareprice:  1003450
growth:  1.0003758450282283
vaultBalance:  54367461638878
earned!
      √ Farmer should earn money

  1 passing (1m)
```

USDC: `npx hardhat test test/bdp/usdc.js`
```
  BDP: USDC
Impersonating...
0xf00dD244228F51547f0563e60bCa65a30FBF5f7f
0x58E99d69613Fa715B2b61Ed19960eCBA7Ed41Cd8
Fetching Underlying at:  0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48
New Vault Deployed:  0xc228F1712588D45c6D689315Cc1A3e96aD4B2146
Strategy Deployed:  0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512
Strategy and vault added to Controller.
    Happy path
loop  0
old shareprice:  1000000
new shareprice:  1000000
growth:  1
loop  1
old shareprice:  1000000
new shareprice:  1000483
growth:  1.000483
loop  2
old shareprice:  1000483
new shareprice:  1000966
growth:  1.0004827668236242
loop  3
old shareprice:  1000966
new shareprice:  1001448
growth:  1.000481534837347
loop  4
old shareprice:  1001448
new shareprice:  1001928
growth:  1.0004793059649628
loop  5
old shareprice:  1001928
new shareprice:  1002407
growth:  1.0004780782651048
loop  6
old shareprice:  1002407
new shareprice:  1002885
growth:  1.0004768522167145
loop  7
old shareprice:  1002885
new shareprice:  1003362
growth:  1.0004756278137572
loop  8
old shareprice:  1003362
new shareprice:  1003838
growth:  1.0004744050502212
loop  9
old shareprice:  1003838
new shareprice:  1004312
growth:  1.0004721877434406
vaultBalance:  26660472772139
earned!
      √ Farmer should earn money

  1 passing (1m)
```

### CODE REVIEW

**Comment by breadforthepeople** [comment]
Thanks! However, the priority of this is kind of low, so probably won't have a chance to get this in at this time.

**Comment by JasperSlimmens** [comment]
Alright, I understand. What about their liquidity pools, for degen strats? These will be getting rewards for 3 months.

I also had a bit of a look at the Alchemix project. It looks good. Might be interesting.

I know priority is not on these normal/degen eth strats right now, but thought it might be good to keep releasing them for good opportunities aswell.

I do have a curve USDP strat ready. I'll put that up tomorrow. It's usdp/3pool liquidity on curve with 50% apy.

I guess just let me know if any strategy seems of interest. I can get them to you quite quickly generally.

**Comment by breadforthepeople** [comment]
Yes we will be releasing the USDP strategy shortly.
Yes, the Alchemix project is interesting. Which farms https://app.alchemix.fi/farms would you recommend adding?

> What about their liquidity pools, for degen strats? These will be getting rewards for 3 months.

Yeah, we could consider these, potentially using 100% FARM buyback for these. Which ones would you think make the most sense?

**Comment by JasperSlimmens** [comment]
Below are the current reward rates for the Alchemix farms. I think the `alUSD` seems pretty stable. It has huge liquidity with `3Crv` of $274m total liquidity. So I think this is stable enough to farm with a normal compounding strategy. The single asset vault has the same APR as the LP, and I expect this to stay this way because people will move from one to the other to get the best yield. We could choose 1 to farm with Harvest. The LP might be best because of the liquidity size providing stability in rewards.

`ALCX` is much less stable. It might be overpriced, and could crash. So farming this might make more sense in 100% buyback form. This also allows farming a single asset vault, but I do not necessarily see the upside of this, as we expect `ALCX` to be the unstable token. So when it crashes you are actually slightly better of holding LP than only holding the token. Rewards for LP are also much higher, so I would recommend 100% buyback on the `[WETH]-[ALCX] SLP`.

```
alUSD Price: $1.00 Market Cap: $170,174,403.10
Staked: 30172994.2561 alUSD ($30,172,994.26)
ALCX Per Week: 884.60 ($633,437.58)
APR: Day 0.30% Week 2.10% Year 109.17%
You are staking 0.00 alUSD ($0.00), 0.00% of the pool.
Staking Contract
Deposit 0.00 alUSD
Withdraw 0.00 alUSD
Claim 0.00 ALCX ($0.00)
Staking or unstaking also claims rewards.


ALCX Price: $716.07 Market Cap: $704,954,178.58
Staked: 15465.7089 ALCX ($11,074,530.16)
ALCX Per Week: 884.60 ($633,437.58)
APR: Day 0.82% Week 5.72% Year 297.43%
You are staking 0.00 ALCX ($0.00), 0.00% of the pool.
Staking Contract
Deposit 0.00 ALCX
Withdraw 0.00 ALCX
Claim 0.00 ALCX ($0.00)
Staking or unstaking also claims rewards.


[WETH]-[ALCX] SLP [+] [-] [<=>] Price: $2,305.25 TVL: $47,698,085.00
WETH Price: $1,745.14
ALCX Price: $716.07
Staked: 18304.5430 SLP ($42,196,584.70)
ALCX Per Week: 7961.43 ($5,700,938.26)
APR: Day 1.93% Week 13.51% Year 702.54%
You are staking 0.00 [WETH]-[ALCX] SLP ($0.00), 0.00% of the pool.
Staking Contract
Deposit 0.00 [WETH]-[ALCX] SLP
Withdraw 0.00 [WETH]-[ALCX] SLP
Claim 0.00 ALCX ($0.00)
Staking or unstaking also claims rewards.


alUSD3CRV-f Price: $1.00 Market Cap: $273,891,960.94
Staked: 273166740.3299 alUSD3CRV-f ($273,863,350.13)
ALCX Per Week: 7961.43 ($5,700,938.26)
APR: Day 0.30% Week 2.08% Year 108.25%
You are staking 0.00 alUSD3CRV-f ($0.00), 0.00% of the pool.
Staking Contract
Deposit 0.00 alUSD3CRV-f
Withdraw 0.00 alUSD3CRV-f
Claim 0.00 ALCX ($0.00)
Staking or unstaking also claims rewards.
```

Then for BDP. Below are the LP pools I was talking about. The rewards are very high right now. Farming wise I think this could be regarded as the seigniorage pools we have had before. `bALPHA` is probably comming down in price a lot in the near future. It might be good to wait till `BDP` distribution has stopped for a few days to see what happens to the protocol. If it somewhat holds up or resettles I think farming these both with 100% buyback could be a good opportunity.

```
[WETH]-[BDP] Uni LP [+] [-] [<=>] Price: $153.15 TVL: $46,020,792.78
WETH Price: $1,750.34
BDP Price: $2.98
Staked: 298417.8077 UNI-V2 ($45,702,931.31)
bALPHA Per Week: 3107.39 ($8,969,094.11)
APR: Day 2.80% Week 19.62% Year 1020.49%
You are staking 0.00 [WETH]-[BDP] Uni LP ($0.00), 0.00% of the pool.
Stake 0.00 [WETH]-[BDP] Uni LP
Unstake 0.00 [WETH]-[BDP] Uni LP
Claim 0.00 bALPHA ($0.00)
Staking or unstaking also claims rewards.


[bALPHA]-[WETH] Uni LP [+] [-] [<=>] Price: $4,679.80 TVL: $10,834,470.50
bALPHA Price: $2,886.38
WETH Price: $1,750.34
Staked: 2270.0443 UNI-V2 ($10,623,346.45)
bALPHA Per Week: 1553.69 ($4,484,547.05)
APR: Day 6.03% Week 42.21% Year 2195.13%
You are staking 0.00 [bALPHA]-[WETH] Uni LP ($0.00), 0.00% of the pool.
Stake 0.00 [bALPHA]-[WETH] Uni LP
Unstake 0.00 [bALPHA]-[WETH] Uni LP
Claim 0.00 bALPHA ($0.00)
Staking or unstaking also claims rewards.
```

**Comment by breadforthepeople** [comment]
Sounds good. We will review both projects and let you know which one we would proceed with.
Thank you!

**Comment by rwqwty93** [comment]
(synced offline)
Closing this PR.

**Pull request closed without merging**
