### PR TITLE
ETH only strategy - single sided farming on Sushi using Liquidity Nexus

### PR DESCRIPTION
**Pull request by DanielZlotin**
This is an ETH-only strategy (deposit ETH, earn ETH) that has (at the time of writing) **33.19% APR**  (**39.36% APY**). Note that this is after paying Harvest's profit fee.

It works by doing single-sided farming of Sushi LP ETH/USDC, so it's basically the same APR as Sushi LP ETH/USDC but uses ETH alone. This outperforms most ETH-only strategies (like supplying ETH to Compound) that usually give single digit APR.

Our team has been working hard to implement single-sided farming in order to enable these ETH strategies. We are fans of harvest.finance and have been participating in harvest as farmers almost since launch. We would like harvest to be the first place where we launch this strategy.

The full concept is described in detail in [contracts/strategies/nexus/README.md](https://github.com/orbs-network/nexus-harvestfinance/tree/master/contracts/strategies/nexus). We will also be happy to discuss in person via Telegram - username [@talkol](https://t.me/talkol) or Discord - username [talkol#2926](https://discordapp.com/users/780436847188246608).

Test:
`test/nexus/nexus-sushi-weth.js` Block number: 12265000

```
  LiquidityNexus SushiSwap: WETH
on block number 12265000
Impersonating...
0xf1fD5233E60E7Ef797025FE9DD066d60d59BcB92
0xf00dD244228F51547f0563e60bCa65a30FBF5f7f
0xBE0eB53F46cd790Cd13851d5EFf43D12404d33E8
New Vault Deployed:  0xd88E80f91a1F5ffC0b86f65C88b70dCaa492C557
Strategy Deployed:  0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512
Strategy and vault added to Controller.
farmer enters LiquidityNexus with 1000 ETH
farmer deposits NexusLP to Vault
loop  0
old shareprice:  1000000000000000000
new shareprice:  1000227950034590539
growth:  1.0002279500345905
loop  1
old shareprice:  1000000000000000000
new shareprice:  1000455807966494308
growth:  1.0004558079664942
loop  2
old shareprice:  1000000000000000000
new shareprice:  1000683712978325047
growth:  1.000683712978325
loop  3
old shareprice:  1000000000000000000
new shareprice:  1000911665077608434
growth:  1.0009116650776084
loop  4
old shareprice:  1000000000000000000
new shareprice:  1001139664272337340
growth:  1.0011396642723374
loop  5
old shareprice:  1000000000000000000
new shareprice:  1001367710570037846
growth:  1.0013677105700378
loop  6
old shareprice:  1000000000000000000
new shareprice:  1001595803978236287
growth:  1.0015958039782362
loop  7
old shareprice:  1000000000000000000
new shareprice:  1001823944504459229
growth:  1.0018239445044592
loop  8
old shareprice:  1000000000000000000
new shareprice:  1002052132156233410
growth:  1.0020521321562335
loop  9
old shareprice:  1000000000000000000
new shareprice:  1002280366941085797
growth:  1.0022803669410858
vaultBalance:  0.034947014553915009
farmer withdraws from Vault
farmer exits LiquidityNexus...
start ETH balance 10000
end ETH balance 10004.547874314234330043
principal 1000 ETH
profit 4.547874314234330043 ETH
Test duration 120 hours
profit percent 0.454787431423433 %
daily percent yield 0.0909574862846866 %
APR 33.1994824939106 %
APY 39.36404528474766 %
earned!
    ✓ Farmer should earn (40336ms)
```

### CODE REVIEW

**Comment by talkol** [comment]
To the moon!

**Comment by amihaz** [comment]
Exciting!

**Comment by CryptJS13** [comment]
Hey Daniel, just for my understanding, is this strategy guaranteed profitable in ETH. As in, is there no chance the user would withdraw less ETH than they deposited if ETH price rises? I am asking because this is the inherit risk of providing liquidity in a pair. How are you dealing with IL?

**Comment by talkol** [comment]
Hi @CryptJS13,

I'm one of the contributors to this PR.

Every liquidity provider has IL risk. This is true for all existing Sushi LP strategies in Harvest. This is not different in this vault. If ETH price rises, the liquidity provider will experience a small loss. This loss is normally mitigated by swap fees alone (particularly in pairs like ETH/USDC), and with the extra SUSHI rewards, risk for loss drops further. If this wasn't the case, all liquidity providers would lose money being LPs.

The USDC needed for farming is supplied by the contract and is regarded as a loan. This means all IL is on the ETH side but in return it takes 80% of the rewards for supplying only 50% of the capital. This makes the APY even higher than traditional ETH/USDC farming.

This [Medium post](https://talkol.medium.com/single-sided-farming-on-any-dex-via-orbs-liquidity-nexus-part-2-824e58057cb5) which is linked in the README goes into great detail about the IL split with exact tables simulating various changes to ETH price. Please take a look at the numbers to see exactly how IL behaves.

**Comment by CryptJS13** [comment]
@talkol Thanks for your reaction. The article explains it very well.

My concern was calling it an single asset ETH strategy, which it technically is ofcourse, and the exposure to IL. I am aware of IL and (hopefully) LP providers are to. This is the exact reason that some people do choose to deposit single assets. They do not want to take that risk. It should be very clear to users that they are taking this risk even though they only deposit ETH.

Now this is not directly Harvests problem, as users will be staking the LP token which will only go up. And it seems you guys are doing a very good job at explaining it at your end.

Very interesting concept indeed and nice work on the strategy. I expect someone from the core dev team will review this in the near future. Thanks for your contribution guys!

**Comment by talkol** [comment]
@CryptJS13 that's an excellent observation nevertheless. People should definitely understand that there is IL risk for them before participating and I'm sure some participants won't consider it unless it's noted clearly in the UI.

One of the things I've never understood is how most AMMs don't clearly explain IL in their UI. In the Uniswap/SushiSwap Add Liquidity interface it's not super straightforward to see and when you remove your liquidity, they don't normally analyze how much IL you had. Also in their APY pages (like Sushi farming page) they usually measure fees and rewards but don't subtract IL..

**Comment by breadforthepeople** [comment]
There does not seem to be any liquidity still. Closing.

**Comment by talkol** [comment]
@breadforthepeople I think there's a misunderstanding. There's a dedicated Nexus contract instance per vault. We do not add the liquidity into the contract for this vault until the code is reviewed and approved.

We should reopen the PR or discuss in Discord (in channel #orbs-harvest)

**Comment by DanielZlotin** [comment]
Please reopen, this is still relevant. We will add liquidity as soon as this strategy is reviewed.
The APY this brings to harvest is far above anything currently available for ETH-only strategies

**Pull request closed without merging**
